export type Value =
  string | number | boolean | null | Value[] | { [key: string]: Value };

export function isDateField(path: string): boolean {
  return path === "general.siteStartDate";
}

export function isCardCollection(path: string): boolean {
  return [
    "profile.links",
    "general.keywords",
    "seo.keywords",
    "navigation",
    "banner.desktop",
    "banner.mobile",
    "sidebar.widgets",
  ].includes(path) || path.endsWith(".children");
}

export function summarizeValue(value: Value): string {
  if (typeof value === "string") return value || "未填写";
  if (Array.isArray(value)) return `${value.length} 项`;
  if (value && typeof value === "object") {
    const record = value as Record<string, Value>;
    return [record.name, record.label, record.title, record.url]
      .filter((item): item is string => typeof item === "string" && item.length > 0)
      .join(" · ") || "未填写";
  }
  return value === null ? "未填写" : String(value);
}
export const labels: Record<string, string> = {
  general: "常规",
  profile: "个人资料",
  appearance: "外观",
  banner: "横幅",
  navigation: "导航",
  sidebar: "侧栏",
  announcement: "公告",
  footer: "页脚",
  seo: "SEO",
  analytics: "统计",
  article: "文章",
  dashboard: "仪表盘",
  siteName: "站点名称",
  siteUrl: "站点网址",
  subtitle: "副标题",
  description: "描述",
  keywords: "关键词",
  timezone: "时区",
  language: "语言",
  favicon: "网站图标",
  siteStartDate: "建站日期",
  avatar: "头像",
  name: "名称",
  bio: "简介",
  email: "邮箱",
  links: "链接",
  icon: "图标",
  url: "网址",
  themeHue: "主题色相",
  themeStyle: "主题风格",
  themeSpec: "主题规范",
  defaultMode: "默认明暗模式",
  allowModeSwitch: "允许切换明暗模式",
  backgroundMode: "背景模式",
  texture: "纹理",
  preset: "预设",
  opacity: "透明度",
  allowMotion: "允许动态效果",
  topAppBarAlign: "顶栏对齐",
  progressIndicatorStyle: "进度条样式",
  postList: "文章列表",
  layout: "布局",
  cover: "封面位置",
  cardWidth: "卡片宽度",
  desktop: "桌面横幅图片",
  mobile: "手机横幅图片",
  position: "位置",
  height: "高度",
  dim: "遮罩",
  enable: "启用",
  homeText: "首页文字",
  title: "标题",
  subtitles: "副标题列表",
  typewriter: "打字机",
  speed: "速度",
  deleteSpeed: "删除速度",
  pauseTime: "停留时间（毫秒）",
  loop: "循环",
  carousel: "轮播",
  interval: "间隔（毫秒）",
  fadeDuration: "渐变时长",
  animation: "动画",
  waves: "波浪",
  id: "标识",
  label: "名称",
  type: "类型",
  target: "目标",
  openInNewTab: "新窗口打开",
  children: "子菜单",
  arrangement: "侧栏布局",
  side: "位置",
  widgets: "组件",
  slot: "位置",
  column: "列",
  pages: "显示页面",
  collapseAfter: "折叠数量",
  content: "内容",
  closable: "允许关闭",
  link: "链接",
  text: "文字",
  external: "外部链接",
  html: "HTML",
  titleSeparator: "标题分隔符",
  defaultDescription: "默认描述",
  ogImage: "社交分享图片",
  twitterHandle: "Twitter 账号",
  extraRobots: "额外 robots 规则",
  umami: "Umami",
  shareUrl: "分享地址",
  websiteId: "网站 ID",
  scriptUrl: "脚本地址",
  pageSize: "每页文章数",
  toc: "目录",
  depth: "深度",
  lastUpdated: "更新提醒",
  minimumAgeDays: "最小天数",
  discovery: "文章推荐",
  relatedCount: "相关文章数",
  randomCount: "随机文章数",
  share: "分享",
  includeCover: "包含封面",
  seriesCardPosition: "系列卡片位置",
  x: "横坐标",
  y: "纵坐标",
  w: "宽度",
  h: "高度",
  visible: "显示",
};
export const choices: Record<string, string[]> = {
  themeStyle: [
    "tonalSpot",
    "vibrant",
    "content",
    "expressive",
    "rainbow",
    "fruitSalad",
    "monochrome",
    "neutral",
    "fidelity",
  ],
  themeSpec: ["2021", "2025"],
  defaultMode: ["light", "dark", "system"],
  backgroundMode: ["banner", "none"],
  preset: [
    "none",
    "starlight",
    "cyberDots",
    "topography",
    "geometric",
    "sakura",
  ],
  topAppBarAlign: ["left", "center"],
  progressIndicatorStyle: ["dual", "single"],
  layout: ["list", "grid"],
  cover: ["left", "right"],
  cardWidth: ["compact", "regular", "relaxed"],
  position: ["top", "center", "bottom"],
  height: ["short", "default", "tall"],
  animation: ["kenBurns", "zoomIn", "zoomOut", "panLeft", "panRight", "none"],
  arrangement: ["single", "dual"],
  side: ["left", "right"],
  slot: ["top", "sticky"],
  column: ["primary", "secondary"],
  seriesCardPosition: ["top", "bottom"],
};
export function template(path: string): Value {
  if (path === "navigation" || path.endsWith(".children"))
    return {
      id: crypto.randomUUID(),
      label: "新链接",
      icon: "",
      type: "url",
      target: "",
      openInNewTab: false,
      children: [],
    };
  if (path === "profile.links") return { name: "", icon: "", url: "" };
  if (path === "sidebar.widgets")
    return {
      type: "recentPosts",
      enable: true,
      slot: "sticky",
      column: "primary",
      pages: [],
      collapseAfter: null,
    };
  return "";
}
export const sidebarPages = [
  "home",
  "archive",
  "categories",
  "tags",
  "series",
  "post",
  "page",
  "search",
  "rss",
  "notFound",
];
