<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>CashewBlog.Infrastructure</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CashewBlog.Application\CashewBlog.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Markdig" />
    <PackageReference Include="HtmlSanitizer" />
    <PackageReference Include="SixLabors.ImageSharp" />
    <PackageReference Include="Konscious.Security.Cryptography.Argon2" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="CashewBlog.UnitTests" />
  </ItemGroup>
</Project>
