<script setup lang="ts">
import { onMounted, onBeforeUnmount, reactive, ref, computed, watch } from "vue";
import { onBeforeRouteLeave, useRoute, useRouter } from "vue-router";
import { useConfirm } from "primevue/useconfirm";
import Drawer from "primevue/drawer";
import MarkdownEditor from "../components/MarkdownEditor.vue";
import MediaPickerDialog from "../components/MediaPickerDialog.vue";
import PostCoverField from "../components/PostCoverField.vue";
import { markdownExcerpt } from "../editor/markdown-document";
import type {
  AdminPostDto,
  UpsertPostRequest,
  AdminCategoryDto,
  AdminTagDto,
  AdminSeriesDto,
  MediaAssetDto,
} from "../api/types";
import { http, request } from "../api/http";
import { attempt, statusLabel, statusSeverity, dateLabel, failure, errorMessage } from "../state";
const route = useRoute(),
  router = useRouter(),
  confirm = useConfirm();
const id = ref(route.params.id === "new" ? null : String(route.params.id));
const post = ref<AdminPostDto>(),
  busy = ref(false),
  ready = ref(false),
  autosaveState = ref("未保存");
const categories = ref<AdminCategoryDto[]>([]),
  tags = ref<string[]>([]),
  tagSuggestions = ref<string[]>([]),
  series = ref<AdminSeriesDto[]>([]);
const model = reactive<UpsertPostRequest>({
  title: "",
  slug: "",
  description: "",
  contentMarkdown: "",
  coverMediaId: null,
  categoryId: null,
  seriesId: null,
  seriesOrder: null,
  tags: [],
  isPinned: false,
  seoTitle: "",
  seoDescription: "",
});
const coverVisible = ref(false),
  settingsVisible = ref(false),
  coverUrl = ref(""),
  descriptionEdited = ref(false);
const siteOrigin = window.location.origin;
const savedBody = ref(""),
  savedContent = ref(""),
  savedTitle = ref("");
const dirty = computed(
  () => ready.value && JSON.stringify(model) !== savedBody.value,
);
const contentDirty = computed(
  () =>
    model.contentMarkdown !== savedContent.value ||
    (post.value?.status === "draft" && model.title !== savedTitle.value),
);
let timer: ReturnType<typeof setInterval> | undefined,
  saving: Promise<void> | null = null,
  allowLeave = false;
function applyDto(dto: AdminPostDto) {
  post.value = dto;
  autosaveState.value = dto.hasWorkingCopy
    ? "已恢复自动保存的工作副本"
    : "已保存";
  Object.assign(model, {
    title: dto.title,
    slug: dto.slug,
    description: dto.description,
    contentMarkdown: dto.editingContentMarkdown ?? dto.contentMarkdown,
    coverMediaId: dto.coverMediaId,
    categoryId: dto.categoryId,
    seriesId: dto.seriesId,
    seriesOrder: dto.seriesOrder,
    tags: dto.tags.map((t) => t.name),
    isPinned: dto.isPinned,
    seoTitle: dto.seoTitle,
    seoDescription: dto.seoDescription,
  });
  coverUrl.value = dto.cover?.url ?? "";
  descriptionEdited.value = Boolean(dto.description?.trim());
  savedBody.value = JSON.stringify(model);
  savedContent.value = model.contentMarkdown;
  savedTitle.value = model.title;
}
async function save(action?: "publish" | "private" | "draft") {
  if (busy.value) return;
  if (!model.title.trim()) {
    failure.value = "请输入文章标题（最多 200 个字符）";
    return;
  }
  busy.value = true;
  await attempt(async () => {
    await saving;
    const body = JSON.parse(JSON.stringify(model)) as UpsertPostRequest;
    // Slugs are generated by the API for new posts and remain stable for existing posts.
    body.slug = null;
    let dto: AdminPostDto;
    if (!id.value) {
      dto = await http.post<AdminPostDto>("/api/admin/posts", body);
      id.value = dto.id;
      post.value = dto;
      if (action)
        dto = await http.post<AdminPostDto>(
          `/api/admin/posts/${id.value}/${action}`,
          body,
        );
    } else
      dto = action
        ? await http.post<AdminPostDto>(
            `/api/admin/posts/${id.value}/${action}`,
            body,
          )
        : await http.put<AdminPostDto>(`/api/admin/posts/${id.value}`, body);
    applyDto(dto);
    autosaveState.value = "已保存";
    if (route.params.id === "new") {
      allowLeave = true;
      await router.replace(`/admin/posts/${dto.id}`);
    }
  });
  busy.value = false;
}
async function autosave(keepalive = false) {
  if (!id.value || !contentDirty.value || busy.value) return;
  if (saving) return saving;
  const body = { contentMarkdown: model.contentMarkdown, title: model.title };
  autosaveState.value = "自动保存中…";
  saving = (async () => {
    try {
      await request("POST", `/api/admin/posts/${id.value}/autosave`, {
        body,
        keepalive,
      });
      savedContent.value = body.contentMarkdown;
      savedTitle.value = body.title;
      autosaveState.value = "正文已自动保存；元数据需点击保存";
    } catch (error) {
      autosaveState.value = "自动保存失败";
      failure.value = errorMessage(error);
    } finally {
      saving = null;
    }
  })();
  return saving;
}
async function preview() {
  if (!id.value) {
    failure.value = "请先保存草稿后预览";
    return;
  }
  const target = window.open("about:blank", "_blank");
  if (target) target.opener = null;
  await autosave();
  if (contentDirty.value) {
    target?.close();
    return;
  }
  if (target)
    target.location.href = `/posts/${encodeURIComponent(post.value!.slug)}?preview=true`;
}
function completeTags(event: { query: string }) {
  const query = event.query.trim().toLocaleLowerCase();
  tagSuggestions.value = tags.value.filter((name) =>
    name.toLocaleLowerCase().includes(query),
  );
}
function addTag(event: KeyboardEvent) {
  const input = event.target as HTMLInputElement;
  const typed = input.value.trim();
  if (!typed) return;
  const name = tags.value.find(
    (tag) => tag.toLocaleLowerCase() === typed.toLocaleLowerCase(),
  ) ?? typed;
  if (!model.tags!.some((tag) => tag.toLocaleLowerCase() === name.toLocaleLowerCase()))
    model.tags!.push(name);
  if (!tags.value.some((tag) => tag.toLocaleLowerCase() === name.toLocaleLowerCase()))
    tags.value.push(name);
  input.value = "";
}
watch(
  () => model.contentMarkdown,
  (markdown) => {
    if (!descriptionEdited.value) model.description = markdownExcerpt(markdown);
  },
);
function selectCover(asset: MediaAssetDto) {
  model.coverMediaId = asset.id;
  coverUrl.value = asset.url;
  coverVisible.value = false;
}
async function confirmPublish() {
  await save("publish");
  if (post.value?.status === "published") settingsVisible.value = false;
}
function beforeUnload(event: BeforeUnloadEvent) {
  if (dirty.value) {
    void autosave(true);
    event.preventDefault();
    event.returnValue = "";
  }
}
function blur() {
  void autosave(true);
}
onBeforeRouteLeave(async () => {
  if (allowLeave || !dirty.value) return true;
  await autosave();
  return new Promise<boolean>((resolve) =>
    confirm.require({
      header: "离开编辑器",
      message: "正文已尝试自动保存。尚未明确保存的元数据会丢失，确定离开？",
      acceptLabel: "离开",
      rejectLabel: "继续编辑",
      accept: () => resolve(true),
      reject: () => resolve(false),
      onHide: () => resolve(false),
    }),
  );
});
onMounted(async () => {
  await attempt(async () => {
    const [cats, tagList, seriesList] = await Promise.all([
      http.get<AdminCategoryDto[]>("/api/admin/categories"),
      http.get<AdminTagDto[]>("/api/admin/tags"),
      http.get<AdminSeriesDto[]>("/api/admin/series"),
    ]);
    categories.value = cats;
    tags.value = tagList.map((t) => t.name);
    series.value = seriesList;
    if (id.value)
      applyDto(await http.get<AdminPostDto>(`/api/admin/posts/${id.value}`));
    else savedBody.value = JSON.stringify(model);
    ready.value = true;
  });
  timer = setInterval(() => void autosave(), 30000);
  window.addEventListener("beforeunload", beforeUnload);
  window.addEventListener("blur", blur);
});
onBeforeUnmount(() => {
  clearInterval(timer);
  window.removeEventListener("beforeunload", beforeUnload);
  window.removeEventListener("blur", blur);
});
</script>
<template>
  <Toolbar
    class="!flex-nowrap"
    ><template #start
      ><div class="flex shrink-0 items-center gap-0.5">
        <Button
          icon="pi pi-arrow-left"
          text
          rounded
          severity="secondary"
          aria-label="返回文章列表"
          title="返回文章列表"
          @click="router.push('/admin/posts')" /><Button
          icon="pi pi-external-link"
          text
          rounded
          severity="secondary"
          :disabled="!id"
          aria-label="预览"
          title="预览"
          class="hidden sm:inline-flex"
          @click="preview" /><Button
          icon="pi pi-sliders-h"
          text
          rounded
          :severity="settingsVisible ? 'primary' : 'secondary'"
          aria-label="文章设置"
          title="文章设置"
          @click="settingsVisible = true"
        /></div></template
    >
    <template #center
      ><div class="min-w-0 flex-1">
        <InputText
          v-model="model.title"
          maxlength="200"
          placeholder="文章标题"
          aria-label="标题"
          class="w-full !border-transparent !bg-transparent !text-base !font-semibold"
        /></div
    ></template>
    <template #end
      ><div class="flex shrink-0 items-center justify-end gap-2">
        <Tag
          :value="post ? statusLabel(post.status) : '新草稿'"
          class="hidden sm:inline-flex" /><span
          class="hidden text-xs text-[var(--p-text-muted-color)] xl:inline"
          role="status"
          >{{ autosaveState }}</span
        ><Button
          icon="pi pi-check"
          size="small"
          :loading="busy"
          aria-label="保存"
          title="保存"
          @click="save()"
        />
      </div></template
    ></Toolbar>
  <MarkdownEditor
    v-if="ready"
    v-model="model.contentMarkdown"
    @error="failure = $event"
  />
  <Drawer
    v-model:visible="settingsVisible"
    position="right"
    modal
    class="!w-full sm:!w-[28rem]"
  >
    <template #header>
      <div class="flex min-w-0 items-center gap-2">
        <i class="pi pi-sliders-h text-[var(--p-primary-color)]" aria-hidden="true" />
        <span class="text-lg font-semibold">文章设置</span>
        <Tag
          :value="post ? statusLabel(post.status) : '新草稿'"
          :severity="post ? statusSeverity(post.status) : 'secondary'"
        />
      </div>
    </template>
    <Fluid>
      <div class="flex flex-col gap-4">
        <dl
          v-if="post"
          class="m-0 grid grid-cols-2 gap-x-4 gap-y-3 rounded-xl bg-[var(--p-content-hover-background)] p-4 text-sm"
        >
          <div>
            <dt class="text-xs text-[var(--p-text-muted-color)]">首次发布</dt>
            <dd class="m-0">{{ dateLabel(post.publishedAt) }}</dd>
          </div>
          <div>
            <dt class="text-xs text-[var(--p-text-muted-color)]">最后更新</dt>
            <dd class="m-0">{{ dateLabel(post.updatedAt) }}</dd>
          </div>
          <div>
            <dt class="text-xs text-[var(--p-text-muted-color)]">字数</dt>
            <dd class="m-0 tabular-nums">{{ post.wordCount.toLocaleString("zh-CN") }}</dd>
          </div>
          <div>
            <dt class="text-xs text-[var(--p-text-muted-color)]">浏览</dt>
            <dd class="m-0 tabular-nums">{{ post.viewCount.toLocaleString("zh-CN") }}</dd>
          </div>
          <div class="col-span-2">
            <dt class="text-xs text-[var(--p-text-muted-color)]">固定链接</dt>
            <dd class="m-0 break-all font-mono text-xs">/posts/{{ post.slug }}</dd>
          </div>
        </dl>
        <Message v-if="post?.hasWorkingCopy && post.status !== 'draft'" severity="info" size="small">
          正文有尚未公开的修改，点击「更新发布」后生效。
        </Message>

        <Panel header="封面">
          <PostCoverField
            :src="coverUrl"
            @choose="coverVisible = true"
            @remove="
              model.coverMediaId = null;
              coverUrl = '';
            "
          />
        </Panel>

        <Panel header="内容信息">
          <div class="flex flex-col gap-4">
            <div class="flex flex-col gap-1.5">
              <div class="flex items-baseline justify-between gap-2">
                <label for="post-description" class="text-sm font-medium">摘要</label>
                <small class="tabular-nums text-[var(--p-text-muted-color)]">{{ model.description?.length ?? 0 }}/1000</small>
              </div>
              <Textarea
                id="post-description"
                v-model="model.description"
                auto-resize
                rows="3"
                maxlength="1000"
                @update:model-value="descriptionEdited = true"
              />
              <small class="text-[var(--p-text-muted-color)]">首次根据正文生成；手动编辑后将保留你的内容。</small>
            </div>
            <div class="flex flex-col gap-1.5">
              <label for="post-category" class="text-sm font-medium">分类</label>
              <Select
                v-model="model.categoryId"
                input-id="post-category"
                :options="categories"
                option-label="name"
                option-value="id"
                placeholder="未分类"
                show-clear
              />
            </div>
            <div class="flex flex-col gap-1.5">
              <label for="post-tags" class="text-sm font-medium">标签</label>
              <AutoComplete
                v-model="model.tags"
                input-id="post-tags"
                :suggestions="tagSuggestions"
                multiple
                fluid
                placeholder="搜索或输入新标签"
                @complete="completeTags"
                @keydown.enter.prevent="addTag"
              />
              <small class="text-[var(--p-text-muted-color)]">输入后回车添加；新标签会自动创建。</small>
            </div>
          </div>
        </Panel>

        <Panel header="系列与展示">
          <div class="flex flex-col gap-4">
            <div class="grid grid-cols-[minmax(0,1fr)_7rem] gap-3">
              <div class="flex min-w-0 flex-col gap-1.5">
                <label for="post-series" class="text-sm font-medium">系列</label>
                <Select
                  v-model="model.seriesId"
                  input-id="post-series"
                  :options="series"
                  option-label="title"
                  option-value="id"
                  placeholder="不属于系列"
                  show-clear
                />
              </div>
              <div class="flex flex-col gap-1.5">
                <label for="post-series-order" class="text-sm font-medium">顺序</label>
                <InputNumber
                  v-model="model.seriesOrder"
                  input-id="post-series-order"
                  :min="1"
                  :disabled="!model.seriesId"
                  placeholder="—"
                />
              </div>
            </div>
            <div class="flex items-center justify-between gap-4">
              <div>
                <label for="post-pinned" class="text-sm font-medium">置顶</label>
                <p class="m-0 text-xs text-[var(--p-text-muted-color)]">在首页和文章列表中优先展示</p>
              </div>
              <ToggleSwitch v-model="model.isPinned" input-id="post-pinned" />
            </div>
          </div>
        </Panel>

        <Panel header="搜索引擎优化" toggleable :collapsed="!model.seoTitle && !model.seoDescription">
          <div class="flex flex-col gap-4">
            <div class="flex flex-col gap-1.5">
              <div class="flex items-baseline justify-between gap-2">
                <label for="post-seo-title" class="text-sm font-medium">SEO 标题</label>
                <small class="tabular-nums text-[var(--p-text-muted-color)]">{{ model.seoTitle?.length ?? 0 }}/200</small>
              </div>
              <InputText id="post-seo-title" v-model="model.seoTitle" maxlength="200" :placeholder="model.title || '默认使用文章标题'" />
            </div>
            <div class="flex flex-col gap-1.5">
              <div class="flex items-baseline justify-between gap-2">
                <label for="post-seo-description" class="text-sm font-medium">SEO 描述</label>
                <small class="tabular-nums text-[var(--p-text-muted-color)]">{{ model.seoDescription?.length ?? 0 }}/500</small>
              </div>
              <Textarea
                id="post-seo-description"
                v-model="model.seoDescription"
                maxlength="500"
                rows="3"
                auto-resize
                placeholder="默认使用摘要"
              />
            </div>
            <div class="rounded-lg border border-[var(--p-content-border-color)] p-3" aria-label="搜索结果预览">
              <div class="mb-1 text-xs text-[var(--p-text-muted-color)]">搜索结果预览</div>
              <div class="truncate font-medium text-[var(--p-primary-color)]">{{ model.seoTitle || model.title || "文章标题" }}</div>
              <div class="truncate font-mono text-xs text-[var(--p-text-muted-color)]">{{ siteOrigin }}/posts/{{ post?.slug ?? "…" }}</div>
              <p class="m-0 mt-1 line-clamp-2 text-sm text-[var(--p-text-muted-color)]">
                {{ model.seoDescription || model.description || post?.excerpt || "尚无描述" }}
              </p>
            </div>
          </div>
        </Panel>
      </div>
    </Fluid>
    <template #footer>
      <div class="flex flex-col gap-2">
        <Button
          icon="pi pi-send"
          :label="post?.status === 'published' ? '更新发布' : '发布'"
          severity="success"
          class="w-full"
          :loading="busy"
          @click="confirmPublish"
        />
        <div class="flex flex-wrap gap-2">
          <Button icon="pi pi-check" label="保存" outlined class="min-w-0 flex-1" :disabled="busy" @click="save()" />
          <Button
            v-if="post?.status !== 'private'"
            icon="pi pi-lock"
            label="设为私密"
            severity="secondary"
            outlined
            class="min-w-0 flex-1"
            :disabled="busy"
            @click="save('private')"
          />
          <Button
            v-if="post && post.status !== 'draft'"
            icon="pi pi-pencil"
            label="转为草稿"
            severity="secondary"
            outlined
            class="min-w-0 flex-1"
            :disabled="busy"
            @click="save('draft')"
          />
        </div>
      </div>
    </template>
  </Drawer>
  <MediaPickerDialog v-model:visible="coverVisible" header="选择封面" images-only @select="selectCover" />
</template>
